# Generated by Django 4.1.3 on 2022-11-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='dept_headed', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='members', to='employees.department'),
        ),
    ]
