# Generated by Django 4.1.3 on 2022-11-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_chief_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dept_headed', to='employees.employee'),
        ),
    ]
