# Generated by Django 4.1.3 on 2022-11-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_department_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_headed', to='employees.employee'),
        ),
    ]
