# Generated by Django 4.1.3 on 2022-11-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_headed', to='employees.employee'),
        ),
    ]
