# Generated by Django 4.1.3 on 2022-11-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_company_departments_alter_department_chief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='departments',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='company_name', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='employees.company'),
        ),
    ]
